### ISSUE TITLE
[ ASK ] how to get uuid-based-token

### ISSUE THREAD

**Issue by dwilimsius** [401Unauthorized/broadlink-bridge#5]
Halo Stephen, i want to ask you something about the package that you made .. first of all, i am very thank you that you made this .. it really help me so much :smile: .. 

i want to ask you about this, you said
`$ broadlink-bridge start -p <port> -t <uuid-based-token>,<uuid-based-token>,...`

i want to know, how can i get that uuid-based-token ? thanks :pray:

**Comment by 401Unauthorized** [comment]
Hi @dwilimsius,

Glad to hear the project has been helpful, let me know if you have any feature requests as you use it.

The token is something you can create yourself as it is only used for authenticating HTTP requests. It can be as simple (not recommended) as `broadlink-bridge start -p 3000 -t 12345` or using a proper UUID, such as `broadlink-bridge start -p 3000 -t 71451653-bf42-4652-9273-a28673c820c5`.

You can use https://www.uuidgenerator.net/ to quickly generate a UUIDv4 and then copy and paste it into your .env file as `TOKENS=<your-token-here>` or pass it through the CLI like `-t <your-token-here>`.

And all your HTTP requests will then need to contain a header `"Authentication": "Bearer <your-token-here>"`.

-- Stephen

**Comment by dwilimsius** [comment]
Hi @401Unauthorized , ooh i see .. okay Stephen, thank you so much for your response .. i am gonna try it again then :smile:

**Comment by dwilimsius** [comment]
Hi @401Unauthorized .. i want to ask you about this .. 
so, i follow your step to connect my Broadlink to my localdevice .. but when i try to run `$ broadlink-bridge connect -w my_wifi_name -p my_wifi_password -s 3` .. it suddenly make my laptop disconnected from BroadlinkProv and reconnect to my real wifi, and in terminal i saw it stuck at `Attempt to connect my_wifi_name` .. what should i do then ? thanks in advance Stephen

**Comment by 401Unauthorized** [comment]
Looks like you are doing everything correctly!

Some things to note:
1. Make sure you are setting the [correct number](https://github.com/401Unauthorized/broadlink-bridge#connect-a-blaster) which aligns to the the security of your WIFI. `3` is the default and most common but you may have another setting if using an older router. 

2. You will actually only see "Attempting to connect...". There is not going to be a "Connected" or other message in the terminal. The information will be sent to the broadlink device but the blaster will automatically switch from AP mode (where the blaster is making its own wifi called `BroadlinkProv`) to trying to connect to your wifi network. Your computer will automatically disconnect from the blaster and connect to your normal wifi.

3. Make sure the WIFI you are trying to connect to is `2.4GHz`. If you have `2.4Ghz` & `5.0GHz` networks with the same name, the blaster may have issues picking the right one. If possible, name the `2.4GHz` differently.

In order to verify the blaster is connected to WIFI, the simplest option is to log into your router's UI and see if the device is listed.

I'll create a feature request on this project to make the WIFI connection process better so that if possible, it will provide feedback to the user when the device is connected and reachable on the WIFI network.

**Comment by 401Unauthorized** [comment]
@dwilimsius,

Were you able to get the blaster connected and `broadlink-bridge` running?

I'll close out this issue soon but let me know if you need more support.
