### ISSUE TITLE
Issue finding blasters

### ISSUE THREAD

**Issue by juancirino** [401Unauthorized/broadlink-bridge#6]
Hi
First off let me say thank you for this great project I been using it with a bunch of broadlinks-rm and its working great.

I just had a question for something strange that Iam running into. I added like 15 broadlinks. 

Most of the blasters are connecting just fine but Iam I have a few that just wont connect to the server and I dont understand why. Any help you might be able to provide will be really appreciated.

**Comment by 401Unauthorized** [comment]
Hi @juancirino,

Glad to hear the project has been helpful! Let me know if you have any feature requests as you use continue to use it as well.

Here are some ides to look into:
1. For the devices you have, are they all RM Mini 3? Or do you have a mix of different models (such as RM4)?

2. Have you been able to add the blasters to the API server through the API (or manually in the db.json file)?

3. Can you test if the API server is able to communicate with the blaster at all? Manually edit the db.json file to add some fake commands under the device. For instance, you can use [these sample commands](https://github.com/401Unauthorized/broadlink-bridge#get-blastersblaster-iddevicesdevice-idcommands). Hold a camera (or a phone) at the blaster and using the API for [Emit IR Endpoints](https://github.com/401Unauthorized/broadlink-bridge#emit-ir-endpoints) send commands to the blaster. Do you see any of the IR lights blinking?

4. I've observed a similar issue before when the "type" of the blaster is incorrect. Take a look at [this documentation](https://github.com/401Unauthorized/broadlink-bridge#post-blasters) and make sure you are setting the correct "type". When following those steps, you may notice there are [numerous options](https://github.com/401Unauthorized/broadlinkjs-rm/blob/master/index.js#L8) based on the hardware revision of the blaster. For instance, I purchased two "RM Mini 3" devices on Amazon and they were not the same (one was "Broadlink RM Mini 3 D", other was "Broadlink RM Mini 3 E"). I had to update the "type" in the db.json file (either through API or manually) for the blaster that was not working. This may be a trial and error approach to find which is the right one for the model you have.

Hopefully this gets things working! If it does, let me know. If not, I will look into it further to see if any updates are required.

-- Stephen

**Comment by juancirino** [comment]
Stephen

Thanks for the quick response.
1.)All of the devices are Broadlink RM2 Pro Plus

2.)I was able to add the blaster through the API
{
      "id": "7483C248725A",
      "devices": [],
      "name": "7483C248725A",
      "type": "65574",
      "address": "10.7.1.4",
      "port": 80,
      "mac": "74:83:C2:48:72:5A",
      "active": false
    },
3.) When I send commands to this particular device nothing happends the light never blinks. But I have other devices that are just the same that the light blinks and it works perfectly.

4.)Regarding the type I have all of the as 65574 I assume thats correct I am not really sure if what Iam putting in type is coorrect. Cause I assumed that in type what needed to be put was de conversion of the parsedInt for the Broadlink RM2.

Again thanks for all the help

**Comment by 401Unauthorized** [comment]
Thanks for providing this information, I will respond in the same order of the questions:

1. Unfortunately, I don't have a `Broadlink RM2 Pro Plus` so have not tested this with that device. If this issue persists, I will see about obtaining one.

2. This looks fine. Are there any devices IDs in the `devices` array for this blaster? You would need that in order to be able to emit a command on the blaster. You can just manually put a device ID from any of your [devices](https://github.com/401Unauthorized/broadlink-bridge#device-object) that you have in the `db.json` file. 

3. See the comment above. In order to test the IR, since we cannot get it to work in learn mode, we would need to manually add a "device" for the IR blaster to control. After adding one, we can test if the command works to know if this is a communication issue or a learning issue.

4. For the type, it may just need to be trial and error just in case. I would do step 2 & 3 first, to make sure the API server is all setup to communicate with the blaster and emit a random command. Then I would try some of the other types which may be for this blaster: `65817`, `65827`, `65845`, `65861` or `65872`.

**Comment by juancirino** [comment]
Stephen

First again let me thank you for all the help and your willingness to improve this proyect. So I can say with out a doubt your library works great with Broadlink RM2 Pro Plus
After some insane debugging I found the problem. I had to go to the device physically just to find that they gave me the wrong mac and ip for the device so I was trying basically to get to work a device that was not the correct device. So once I got the correct the ip and mac every thing worked great. 
Again thank you for this help. The library so far has no issues.
The issues is with the one using it LOL

**Comment by 401Unauthorized** [comment]
Hi @juancirino,

Of course, I appreciate that the project is being used!

Good to hear you were able to resolve the problem too. It would have taken a while before I would have thought the MAC address was incorrect. I will add that to the list of troubleshooting steps in case someone else has a similar issue in the future.

I'll close out this issue for now. Feel free to raise a new one for any further issues, ideas or questions!

-- Stephen
